import assert from "node:assert/strict";
import test from "node:test";
import type { Agent, ProviderModelCatalog } from "@capyfin/contracts";
import {
  isAutoGeneratedLabel,
  makeUniqueSessionLabel,
  resolveCompatibleAgentModelRef,
} from "./gateway-client.ts";

const baseAgent: Agent = {
  agentDir: "/tmp/main",
  createdAt: new Date(0).toISOString(),
  id: "main",
  instructions: "You are Main.",
  isDefault: true,
  name: "Main",
  updatedAt: new Date(0).toISOString(),
  workspaceDir: "/tmp/workspace",
};

const githubCopilotCatalog: ProviderModelCatalog = {
  currentModelId: "gpt-5-mini",
  currentModelRef: "github-copilot/gpt-5-mini",
  models: [
    {
      isSelected: true,
      label: "GPT-5 mini",
      modelId: "gpt-5-mini",
      modelRef: "github-copilot/gpt-5-mini",
      providerId: "github-copilot",
    },
    {
      isSelected: false,
      label: "GPT-4o",
      modelId: "gpt-4o",
      modelRef: "github-copilot/gpt-4o",
      providerId: "github-copilot",
    },
  ],
  providerId: "github-copilot",
};

void test("resolveCompatibleAgentModelRef ignores stale inherited model ids after provider switch", () => {
  const result = resolveCompatibleAgentModelRef({
    agent: {
      ...baseAgent,
      modelId: "gpt-5.4",
    },
    authOverview: {
      selectedModelId: "gpt-5-mini",
      selectedProviderId: "github-copilot",
    },
    providerCatalog: githubCopilotCatalog,
  });

  assert.equal(result, "github-copilot/gpt-5-mini");
});

void test("resolveCompatibleAgentModelRef does not treat bare inherited model ids as explicit provider models", () => {
  const result = resolveCompatibleAgentModelRef({
    agent: {
      ...baseAgent,
      modelId: "gpt-5.4",
    },
    authOverview: {
      selectedModelId: "gpt-5-mini",
      selectedProviderId: "github-copilot",
    },
    providerCatalog: {
      currentModelRef: "github-copilot/gpt-5-mini",
      models: [
        ...githubCopilotCatalog.models,
        {
          isSelected: false,
          label: "GPT-5.4",
          modelId: "gpt-5.4",
          modelRef: "github-copilot/gpt-5.4",
          providerId: "github-copilot",
        },
      ],
      providerId: "github-copilot",
    },
  });

  assert.equal(result, "github-copilot/gpt-5-mini");
});

void test("resolveCompatibleAgentModelRef preserves valid explicit agent models", () => {
  const result = resolveCompatibleAgentModelRef({
    agent: {
      ...baseAgent,
      modelId: "gpt-4o",
      providerId: "github-copilot",
    },
    authOverview: {
      selectedModelId: "gpt-5-mini",
      selectedProviderId: "github-copilot",
    },
    providerCatalog: githubCopilotCatalog,
  });

  assert.equal(result, "github-copilot/gpt-4o");
});

void test("makeUniqueSessionLabel returns base label when no collision exists", () => {
  assert.equal(
    makeUniqueSessionLabel("Morning Brief", ["Deep Dive", "Market Health"]),
    "Morning Brief",
  );
});

void test("makeUniqueSessionLabel appends the next numeric suffix on collision", () => {
  assert.equal(
    makeUniqueSessionLabel("Morning Brief", [
      "Morning Brief",
      "Morning Brief (2)",
      "Morning Brief (4)",
    ]),
    "Morning Brief (3)",
  );
});

// ---------------------------------------------------------------------------
// isAutoGeneratedLabel
// ---------------------------------------------------------------------------

void test("isAutoGeneratedLabel returns true for undefined", () => {
  assert.equal(isAutoGeneratedLabel(undefined), true);
});

void test("isAutoGeneratedLabel returns true for empty string", () => {
  assert.equal(isAutoGeneratedLabel(""), true);
});

void test("isAutoGeneratedLabel returns true for bare 8-char hex ID", () => {
  assert.equal(isAutoGeneratedLabel("f1a26b39"), true);
});

void test("isAutoGeneratedLabel returns true for UUID-prefix with date suffix", () => {
  assert.equal(isAutoGeneratedLabel("d789933d (2026-03-22)"), true);
});

void test("isAutoGeneratedLabel returns true for uppercase UUID-prefix", () => {
  assert.equal(isAutoGeneratedLabel("D789933D"), true);
});

void test("isAutoGeneratedLabel returns false for human-readable label", () => {
  assert.equal(isAutoGeneratedLabel("Deep Dive: AAPL"), false);
});

void test("isAutoGeneratedLabel returns false for first-message preview", () => {
  assert.equal(
    isAutoGeneratedLabel("which companies release earnings this week?"),
    false,
  );
});

void test("isAutoGeneratedLabel returns false for short hex-like word", () => {
  assert.equal(isAutoGeneratedLabel("abcdef (note)"), false);
});

void test("isAutoGeneratedLabel returns false for label starting with 'Feedback'", () => {
  assert.equal(isAutoGeneratedLabel("Feedback on Q1 report"), false);
});
