/**
 * Static lookup map of common US-listed ticker symbols to company names.
 * Used as a fallback when no financial data provider is connected.
 */
const TICKER_COMPANY_MAP: Record<string, string> = {
  AAPL: "Apple Inc.",
  ABBV: "AbbVie Inc.",
  ABT: "Abbott Laboratories",
  ACN: "Accenture plc",
  ADBE: "Adobe Inc.",
  ADI: "Analog Devices Inc.",
  ADP: "Automatic Data Processing",
  ADSK: "Autodesk Inc.",
  AEP: "American Electric Power",
  AFL: "Aflac Inc.",
  AFRM: "Affirm Holdings",
  AGG: "iShares Core US Aggregate Bond ETF",
  AMAT: "Applied Materials Inc.",
  AMD: "Advanced Micro Devices Inc.",
  AMGN: "Amgen Inc.",
  AMT: "American Tower Corp.",
  AMZN: "Amazon.com Inc.",
  ANET: "Arista Networks Inc.",
  APD: "Air Products & Chemicals",
  APH: "Amphenol Corp.",
  ARKK: "ARK Innovation ETF",
  ASML: "ASML Holding NV",
  AVGO: "Broadcom Inc.",
  AXP: "American Express Co.",
  BA: "Boeing Co.",
  BABA: "Alibaba Group",
  BAC: "Bank of America Corp.",
  BLK: "BlackRock Inc.",
  BMY: "Bristol-Myers Squibb Co.",
  BRK: "Berkshire Hathaway Inc.",
  "BRK.A": "Berkshire Hathaway Inc.",
  "BRK.B": "Berkshire Hathaway Inc.",
  BSX: "Boston Scientific Corp.",
  C: "Citigroup Inc.",
  CAT: "Caterpillar Inc.",
  CCL: "Carnival Corp.",
  CDNS: "Cadence Design Systems",
  CI: "Cigna Group",
  CL: "Colgate-Palmolive Co.",
  CMCSA: "Comcast Corp.",
  CME: "CME Group Inc.",
  CMG: "Chipotle Mexican Grill",
  COF: "Capital One Financial",
  COIN: "Coinbase Global Inc.",
  COP: "ConocoPhillips",
  COST: "Costco Wholesale Corp.",
  CRM: "Salesforce Inc.",
  CRWD: "CrowdStrike Holdings",
  CSCO: "Cisco Systems Inc.",
  CTAS: "Cintas Corp.",
  CVS: "CVS Health Corp.",
  CVX: "Chevron Corp.",
  D: "Dominion Energy Inc.",
  DASH: "DoorDash Inc.",
  DDOG: "Datadog Inc.",
  DE: "Deere & Co.",
  DIA: "SPDR Dow Jones Industrial Average ETF",
  DIS: "Walt Disney Co.",
  DKNG: "DraftKings Inc.",
  DUK: "Duke Energy Corp.",
  DVN: "Devon Energy Corp.",
  EA: "Electronic Arts Inc.",
  EBAY: "eBay Inc.",
  EL: "Estee Lauder Cos.",
  EMR: "Emerson Electric Co.",
  ENPH: "Enphase Energy Inc.",
  EOG: "EOG Resources Inc.",
  EQIX: "Equinix Inc.",
  EW: "Edwards Lifesciences",
  EXC: "Exelon Corp.",
  F: "Ford Motor Co.",
  FANG: "Diamondback Energy",
  FCX: "Freeport-McMoRan Inc.",
  FDX: "FedEx Corp.",
  FSLR: "First Solar Inc.",
  GD: "General Dynamics Corp.",
  GE: "GE Aerospace",
  GILD: "Gilead Sciences Inc.",
  GM: "General Motors Co.",
  GOOG: "Alphabet Inc.",
  GOOGL: "Alphabet Inc.",
  GPN: "Global Payments Inc.",
  GS: "Goldman Sachs Group",
  HD: "Home Depot Inc.",
  HLT: "Hilton Worldwide",
  HON: "Honeywell International",
  HOOD: "Robinhood Markets Inc.",
  IBM: "International Business Machines",
  ICE: "Intercontinental Exchange",
  INTC: "Intel Corp.",
  INTU: "Intuit Inc.",
  ISRG: "Intuitive Surgical Inc.",
  IWM: "iShares Russell 2000 ETF",
  JNJ: "Johnson & Johnson",
  JPM: "JPMorgan Chase & Co.",
  KHC: "Kraft Heinz Co.",
  KLAC: "KLA Corp.",
  KO: "Coca-Cola Co.",
  KVUE: "Kenvue Inc.",
  LIN: "Linde plc",
  LLY: "Eli Lilly and Co.",
  LMT: "Lockheed Martin Corp.",
  LOW: "Lowe's Cos.",
  LRCX: "Lam Research Corp.",
  LULU: "Lululemon Athletica",
  MA: "Mastercard Inc.",
  MAR: "Marriott International",
  MCD: "McDonald's Corp.",
  MCHP: "Microchip Technology",
  MCO: "Moody's Corp.",
  MDLZ: "Mondelez International",
  MDT: "Medtronic plc",
  MET: "MetLife Inc.",
  META: "Meta Platforms Inc.",
  MMM: "3M Co.",
  MO: "Altria Group Inc.",
  MPC: "Marathon Petroleum",
  MRVL: "Marvell Technology",
  MS: "Morgan Stanley",
  MSFT: "Microsoft Corp.",
  MSI: "Motorola Solutions",
  MU: "Micron Technology Inc.",
  NFLX: "Netflix Inc.",
  NKE: "Nike Inc.",
  NOC: "Northrop Grumman Corp.",
  NOW: "ServiceNow Inc.",
  NSC: "Norfolk Southern Corp.",
  NET: "Cloudflare Inc.",
  NVDA: "NVIDIA Corp.",
  NVO: "Novo Nordisk A/S",
  OKE: "ONEOK Inc.",
  ON: "ON Semiconductor",
  ORCL: "Oracle Corp.",
  OXY: "Occidental Petroleum",
  PANW: "Palo Alto Networks",
  PATH: "UiPath Inc.",
  PDD: "PDD Holdings Inc.",
  PEP: "PepsiCo Inc.",
  PFE: "Pfizer Inc.",
  PG: "Procter & Gamble Co.",
  PGR: "Progressive Corp.",
  PINS: "Pinterest Inc.",
  PLTR: "Palantir Technologies",
  PM: "Philip Morris International",
  PSX: "Phillips 66",
  PYPL: "PayPal Holdings Inc.",
  QCOM: "Qualcomm Inc.",
  QQQ: "Invesco QQQ Trust",
  REGN: "Regeneron Pharmaceuticals",
  RIVN: "Rivian Automotive",
  ROKU: "Roku Inc.",
  ROP: "Roper Technologies",
  ROST: "Ross Stores Inc.",
  RTX: "RTX Corp.",
  SBUX: "Starbucks Corp.",
  SCHW: "Charles Schwab Corp.",
  SE: "Sea Ltd.",
  SHOP: "Shopify Inc.",
  SHW: "Sherwin-Williams Co.",
  SLB: "SLB (Schlumberger)",
  SMCI: "Super Micro Computer",
  SNAP: "Snap Inc.",
  SNPS: "Synopsys Inc.",
  SO: "Southern Co.",
  SOFI: "SoFi Technologies",
  SPG: "Simon Property Group",
  SPOT: "Spotify Technology",
  SPY: "SPDR S&P 500 ETF Trust",
  SQ: "Block Inc.",
  SYK: "Stryker Corp.",
  T: "AT&T Inc.",
  TGT: "Target Corp.",
  TJX: "TJX Cos.",
  TMO: "Thermo Fisher Scientific",
  TMUS: "T-Mobile US Inc.",
  TSLA: "Tesla Inc.",
  TSM: "Taiwan Semiconductor",
  TXN: "Texas Instruments Inc.",
  U: "Unity Software Inc.",
  UBER: "Uber Technologies Inc.",
  UNH: "UnitedHealth Group Inc.",
  UNP: "Union Pacific Corp.",
  UPS: "United Parcel Service",
  USB: "U.S. Bancorp",
  V: "Visa Inc.",
  VLO: "Valero Energy Corp.",
  VOO: "Vanguard S&P 500 ETF",
  VRTX: "Vertex Pharmaceuticals",
  VTI: "Vanguard Total Stock Market ETF",
  VZ: "Verizon Communications",
  WBA: "Walgreens Boots Alliance",
  WFC: "Wells Fargo & Co.",
  WM: "Waste Management Inc.",
  WMT: "Walmart Inc.",
  XLF: "Financial Select Sector SPDR Fund",
  XLK: "Technology Select Sector SPDR Fund",
  XOM: "Exxon Mobil Corp.",
  ZM: "Zoom Video Communications",
  ZS: "Zscaler Inc.",
};

/**
 * Look up the company name for a given ticker symbol.
 * Returns undefined if the ticker is not in the static map.
 */
export function lookupCompanyName(ticker: string): string | undefined {
  return TICKER_COMPANY_MAP[ticker.toUpperCase()];
}
